= Guard::AsciiDoc

Guard::AsciiDoc is a plugin for Guard that renders watched AsciiDoc files to the specified output format whenever they change using Asciidoctor.

AsciiDoc:: http://asciidoc.org
Guard:: https://github.com/guard/guard
Asciidoctor:: https://github.com/asciidoctor/asciidoctor

== Installation

Set up your +Gemfile+:

[source,ruby]
.Gemfile
----
source 'https://rubygems.org'

gem 'guard-asciidoc'
gem 'rb-inotify', '~> 0.9'
----

And install the dependencies:

 $ bundle install

Create a +Guardfile+ in the folder you want to watch:

[source,ruby]
.Guardfile
----
guard :asciidoc
----

If you want to watch a folder below the current one, override the default:

[source,ruby]
.Guardfile
----
guard :asciidoc, :watch_dir => 'docs'
----

You can also set AsciiDoc attributes:

[source,ruby]
.Guardfile
----
guard :asciidoc, :attributes => {'toc' => ''}
----

Start Guard:

 $ bundle exec guard

In the pry console, you should see:

 Guard::AsciiDoc has started watching your files
 Guard is now watching at '/path/to/current/directory'

To learn how to setup Guard to send changes directly to the browser, refer to the Asciidoctor tutorial https://github.com/asciidoctor/asciidoctor.github.com/blob/master/docs/editing-with-live-preview.adoc[Editing with Live Preview].

== History

.0.0.5

 * Prerelease
 * Supports Asciidoctor 0.1.1
 * Backends: html5 only (no stylesheet option, yet)
