name: CI
on:
  push:
    branches: [main]
    paths-ignore: ['*.adoc']
  pull_request:
    branches: [main]
    paths-ignore: ['*.adoc']
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: [jruby-9.4, '3.0', '3.2']
        exclude:
        # remove entry to mark as primary
        - os: ubuntu-latest
          ruby: '3.2'
        include:
        - os: ubuntu-latest
          ruby: '3.2'
          primary: primary
    runs-on: ${{ matrix.os }}
    env:
      BUNDLE_WITHOUT: lint
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Enable lint (primary only)
      if: matrix.primary
      run: |
        echo 'BUNDLE_WITHOUT=' >> $GITHUB_ENV
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run linter (primary only)
      if: matrix.primary
      run: bundle exec rake lint
    - name: Run tests
      run: bundle exec ruby -w $(bundle exec ruby -e 'print File.join Gem.bindir, %q(rake)') spec
